### ISSUE TITLE
Default Icinga2 Theme "breaks" the interface

### ISSUE THREAD

**Issue by Fl33Tr** [visgence/icinga2-dependency-module#16]
Using the default Theme of Icingaweb version 2.11.1
![grafik](https://user-images.githubusercontent.com/96236481/183355658-da088bb4-5a3c-4a89-a3f5-0b99197717e4.png)

Using the "high-contrast" Theme
![grafik](https://user-images.githubusercontent.com/96236481/183355973-1ad6fce9-49ef-4124-b85e-32ba24527e42.png)

**Comment by mihadoo** [comment]
I reinstalled icinga2 and I have the same problem. I cannot configure the dependency plugin. Same problem as above.

**Comment by helmo** [comment]
It's a css issue, I've added a fix in #17
